/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrental.gui;

import carrental.model.DBModel;
import carrental.model.IModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author Gabor Farkas <info@gfarkas.com>
 */
public class MainWindow extends javax.swing.JFrame {

    private IModel model;

    public MainWindow() {

        String username = "root";
        String password = "1234";
        String db_url = "jdbc:mysql://localhost:3306/carrental";

        initComponents();
        setVisible(true);
        setTitle("Car Rental manager");
        setSize(800, 600);
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);

        Connection connection = null;

        try {

            connection = DriverManager.getConnection(db_url, username, password);
            model = new DBModel(connection);

        } catch (SQLException e) {

            System.out.println("Database connection error!");
            System.exit(0);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        importMenuItem = new javax.swing.JMenuItem();
        exportMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        carMenu = new javax.swing.JMenu();
        driverMenu = new javax.swing.JMenu();
        rentalMenu = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setText("File");

        importMenuItem.setText("Import");
        fileMenu.add(importMenuItem);

        exportMenuItem.setText("Export");
        fileMenu.add(exportMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        carMenu.setText("Car");
        carMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(carMenu);

        driverMenu.setText("Driver");
        driverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                driverMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(driverMenu);

        rentalMenu.setText("Rental");
        rentalMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rentalMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(rentalMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed

        setVisible(false);

    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void carMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carMenuMouseClicked

        CarJDialog carJDialog = new CarJDialog(this, model);
        carJDialog.setVisible(true);

    }//GEN-LAST:event_carMenuMouseClicked

    private void rentalMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentalMenuMouseClicked

        RentalJDialog rentalJDialog = new RentalJDialog(this, model);
        rentalJDialog.setVisible(true);

    }//GEN-LAST:event_rentalMenuMouseClicked

    private void driverMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_driverMenuMouseClicked

        DriverJDialog driverJDialog = new DriverJDialog(this, model);
        driverJDialog.setVisible(true);

    }//GEN-LAST:event_driverMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    public static void networkError(JDialog jdialog, Exception ex) {

        JOptionPane.showMessageDialog(jdialog.getRootPane(), ex.toString(), "Network error", JOptionPane.ERROR_MESSAGE);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu carMenu;
    private javax.swing.JMenu driverMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exportMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem importMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu rentalMenu;
    // End of variables declaration//GEN-END:variables
}
